// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TemplateWizard
{
    internal sealed partial class Vsix
    {
        public const string Id = "TemplateWizard.e2b8934f-eafb-46e6-937e-bcd2a62b32f2";
        public const string Name = "TemplateWizard";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
